# Generated by Django 5.1.4 on 2025-02-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Famale', 'Female')], default='Male', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(choices=[('Ahemadabad', 'Ahemadabad'), ('Surendernagar', 'Surendernagar'), ('Surat', 'Surat'), ('Bhavanagar', 'Bhavanagar'), ('Gandhinagar', 'Gandhinagar')], default='Ahemadabad', max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('coures', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('take', models.CharField(max_length=50)),
                ('pay_method', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Card', 'Card')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='new.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='new.studentdata')),
            ],
        ),
    ]
