# Generated by Django 5.1.4 on 2025-02-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_remove_note_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
